# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CVtableview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire'
  # Pods for CVtableview

  target 'CVtableviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CVtableviewUITests' do
    # Pods for testing
  end

end
